image:
  name: hashicorp/packer:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - init
  - validate
  - build

variables:
    PACKER_PLUGIN_PATH: .packer.d/plugins
    PROXMOX_API_URL: $PROXMOX_API_URL
    PROXMOX_API_TOKEN_ID: $PROXMOX_API_TOKEN_ID
    PROXMOX_API_TOKEN_SECRET: $PROXMOX_API_TOKEN_SECRET

init:
  stage: init
  tags:
    - docker
  script:
    - mkdir -p .packer.d/plugins
    - packer init packer.pkr.hcl
  artifacts:
    paths:
      - .packer.d/plugins
    expire_in: 1 week

validate:
  stage: validate
  tags:
    - docker
  needs:
    - job: init
      artifacts: true
  script:
    - packer validate ubuntu-server-focal.pkr.hcl
    - packer validate ubuntu-server-jammy.pkr.hcl


build ubuntu-server-focal:
  stage: build
  tags:
    - shell_runner
  needs:
    - job: init
      artifacts: true
    - job: validate
      artifacts: false
  when: manual
  script:
    - RUNNER_IP_ADDRESS=$(hostname -I | awk '{print $1}')
    - HASHED_PASSWORD=$(openssl passwd -6 -salt xyz ${PASSWORD})
    - sed -i "s|PLAINTEXT_PASSWORD|${PASSWORD}|g" ubuntu-server-focal.pkr.hcl
    - sed -i "s|HASHED_PASSWORD|${HASHED_PASSWORD}|g" ubuntu-server-focal/user-data
    - docker run
        -w /workspace
        -v ${PWD}:/workspace
        -e PROXMOX_API_URL="${PROXMOX_API_URL}"
        -e PROXMOX_API_TOKEN_ID="${PROXMOX_API_TOKEN_ID}"
        -e PROXMOX_API_TOKEN_SECRET="${PROXMOX_API_TOKEN_SECRET}"
        -e RUNNER_IP_ADDRESS="${RUNNER_IP_ADDRESS}"
        -e RUNNER_IP_ADDRESS="${RUNNER_IP_ADDRESS}"
        -e PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins
        -p 8800-8810:8800-8810
        hashicorp/packer:latest build ubuntu-server-focal.pkr.hcl

build ubuntu-server-jammy:
  stage: build
  tags:
    - shell_runner
  needs:
    - job: init
      artifacts: true
    - job: validate
      artifacts: false
  when: manual
  script:
    - RUNNER_IP_ADDRESS=$(hostname -I | awk '{print $1}')
    - HASHED_PASSWORD=$(openssl passwd -6 -salt xyz ${PASSWORD})
    - sed -i "s|PLAINTEXT_PASSWORD|${PASSWORD}|g" ubuntu-server-jammy.pkr.hcl
    - sed -i "s|HASHED_PASSWORD|${HASHED_PASSWORD}|g" ubuntu-server-jammy/user-data
    - docker run
        -w /workspace
        -v ${PWD}:/workspace
        -e PROXMOX_API_URL="${PROXMOX_API_URL}"
        -e PROXMOX_API_TOKEN_ID="${PROXMOX_API_TOKEN_ID}"
        -e PROXMOX_API_TOKEN_SECRET="${PROXMOX_API_TOKEN_SECRET}"
        -e RUNNER_IP_ADDRESS="${RUNNER_IP_ADDRESS}"
        -e RUNNER_IP_ADDRESS="${RUNNER_IP_ADDRESS}"
        -e PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins
        -p 8800-8810:8800-8810
        hashicorp/packer:latest build ubuntu-server-focal.pkr.hcl
